### ISSUE TITLE
Explore using ansible playbook for helper node (bastion) setup

### ISSUE THREAD

**Issue by bpradipt** [ocp-power-automation/ocp4-upi-powervm#11]
Updated ansible playbook for helper node setup is available here - https://github.com/RedHatOfficial/ocp4-helpernode
Explore if we can leverage the same ansible playbook and use TF for handling the infra pieces (VM creation, booting etc)

**Comment by yussufsh** [comment]
The ocp4-hellpernode script can be used for various services configurations such as DNS, DHCP, HAProxy, HTTP.
When I try to use the script I see some issues...
1. The main playbook at the end is using `nmcli` commands for setting DNS details on default interface. Since PowerVC VM does not required NetworkManager for assigning IP to the helper node, this will not work as the IP is not getting assigned after reboot on PowerVC.
2. DHCP config does not support specifying multiple allocation-pool. [link](https://github.com/RedHatOfficial/ocp4-helpernode/blob/master/docs/examples/vars.yaml#L15-L16)

**Comment by bpradipt** [comment]
This is fixed by https://github.com/ppc64le/ocp4_upi_powervm/pull/15
