### ISSUE TITLE
Install of OCP 4.5 with Terraform OCP 4.7 fails in bootstrap bringup

### ISSUE THREAD

**Issue by dannert** [ocp-power-automation/ocp4-upi-powervm#211]
OCP 4.7 TF scripts should be able to install OCP 4.5 on POWER.
RHCOS 4.5.4 - only option for OCP 4.5 on Power - bootstrap fails to correctly mount the config drive with the ignition information provided from PowerVC.

log from bootstrap shows:
Jun 18 15:56:12 localhost ignition[872]: config drive ("/dev/disk/by-label/CONFIG-2") not found. Waiting...

Note the "UPPER CASE" spelling in the message. /dev/disk/by-label/config-2 exists and can be successfully mounted and contains correct content.

I do not know where the mount command is driven from or how to debug this further in RHCOS.

Side note - with RHCOS 4.7-latest, this works correctly.

**Comment by yussufsh** [comment]
Use code from [4.5 release branch](https://github.com/ocp-power-automation/ocp4-upi-powervm/tree/release-4.5). This branch also refer to the install playbooks that works only for 4.5. This is because ocp 4.5 uses old ignition version that cannot be used with ocp/rhcos 4.7.

Note that this branch is no longer updated with new features, that said it should work to install ocp 4.5.

**Comment by dannert** [comment]
Ok. Will give that a try. Need back level TF as 0.13 fails with rel 4.5

**Comment by yussufsh** [comment]
Yes it needs terraform 0.12. Please follow the README from that branch.

**Comment by dannert** [comment]
Thx for the clarification re having to use TF 4.5 branch. With that branch and latest TF 0.12 version I was able to successfully install OCP 4.5 with RHCOS 4.5.4.
